### ISSUE TITLE
Errors in commands are suppressed

### ISSUE THREAD

**Issue by hemberger** [pazuzu156/AnubisBot#25]
I'm trying to debug why a call to a custom command is failing, but the call to `index` is silently aborting. I'm using the following `.env` file:
```
DEBUG=true
LOG_TO_FILE=false
LOG_DISCORDPHP=true
NAME=Autopilot
TOKEN=...
DESCRIPTION=
DEFAULT_BOT_PRESENCE=
PREFIX=.
PREFIX_SPACE=false
BOT_OWNER=
```
A skeleton of my `app/commands/NewCommand.php` file is:
```php
<?php

namespace App\Commands;

error_reporting(E_ALL);

use Core\Command\Command;
use Core\Command\Parameters;

class NewCommand extends Command
{
    protected $name = 'newcommand';

    protected $description = 'Custom command';

    public function index(Parameters $p) 
    {   
        // Get the ID of the caller
        $id = $this->author->user->id;
        echo "id=$id\n";
        $name = $this->author->user->username;

        // failing code here
        ...

        $this->channel->sendMessage("Hello $name, your id is $id");
    }   
}
```
I get the output of "id=..." in the stdout, but then nothing else happens. If I remove the failing code, then I get the message sent to the channel as expected.

I should also note that if an error occurs before the call to `index` (e.g. in the class construction, when the file is first loaded?), then I do get an error printed to stdout.

I've looked all around for where the error messages may be dumped, and I've exhausted my limited PHP knowledge. Is there something I'm missing here?

Thanks!

**Comment by pazuzu156** [comment]
Did you add your command to the bot's command registrar? Look in `registrar.php` and make sure it's in the `commands` array

**Comment by hemberger** [comment]
Thanks for the quick response!

Yeah, I have the command registered in registrar.php:
```php
    'commands' => [
        ...

        // Register any of your custom commands here
        App\Commands\NewCommand::class,
    ],
```
The command runs exactly as expected if I remove the failing code. (By the way, when I say "failing code", it can be anything that causes a PHP error -- it is not specific to what the failing code is.)

**Comment by pazuzu156** [comment]
I'm aware of things not being displayed with PHP errors. That's an issue with discordphp and how it handles react. Causing nothing to happen vs crashing the app. Nothing I can do with that unfortunately. I ran your code as is and it ran just fine. Try creating a new command with the command line `php cli make:command NewCommand` but delete your old one. Then place your code back in the index method and see what happens

**Comment by hemberger** [comment]
When you write commands, how do you go about debugging it if there's no way to see any error messages?

**Comment by pazuzu156** [comment]
2 different ways I do it. Using the logger, or using symfony's dump function. You can get the logger in a command by using `$this->app->logger()`

**Comment by hemberger** [comment]
Okay, I've reproduced this error with a trivially simple DiscordPHP bot. I can't get any error messages there either, so I'll close this and focus on seeing if I can resolve the issue upstream.

Thanks!
