### ISSUE TITLE
Heartbeat is logged when DEBUG is false

### ISSUE THREAD

**Issue by hemberger** [pazuzu156/AnubisBot#26]
My `.env` file contains
```
DEBUG=false
```
but I am still getting heartbeat output in my log
```
[2017-11-22 18:10:37] Autopilot.DEBUG: sending heartbeat {"seq":285} []
[2017-11-22 18:10:38] Autopilot.DEBUG: received heartbeat ack {"response_time":105.5459976196289} []
```
Is it possible to disable the logging of these messages?

Thanks!

**Comment by pazuzu156** [comment]
Odd, they shouldn't be logged. I don't ever see that on my end when it's disabled. I'll look into it, but since the php port isn't receiving updates anymore, probably won't be fixed until the c# port is done

**Comment by pazuzu156** [comment]
Closed as won't-fix, due to dropping of PHP
